### ISSUE TITLE
Player keeps moving after key is released

### ISSUE THREAD

**Issue by flokargl** [Nocte-/hexahedra#30]
When jumping while moving and releasing the move key while still holding the jump key, the player continues to move and jump, even though the move key is no longer pressed. Pressing any key stops the player.

**Comment by Nocte-** [comment]
Heh... turns out the player keeps moving because there's not enough time in contact with the ground for the friction force to kick in. So it's not a bug, it's conservation of momentum. ;) And you'll stop eventually because of air resistance.

(I'll fix it. Not sure yet how, though. Could do mid-air steering, could do infinite acceleration/braking, ...)
